all:
	gcc repeater.c -o repeater
	gcc spawn.c -o spawn
	gcc no_fork.c -o no_fork
	gcc doorbell.c -o doorbell
	gcc drop.c -o drop
	gcc greeter.c -o greeter
	gcc incrementer.c -o incrementer
	gcc -pthread polarity.c -o polarity
	gcc sailing.c -o sailing
	gcc sail_4_10.c -o sail_4_10
	gcc -pthread sleeping_giant.c -o sleeping_giant
